# #####################################################################
# Automatically generated by qmake (2.01a) sam. nov. 17 11:36:33 2012
# #####################################################################
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += sql
QT +=ltag
LIBS += -lcv -lhighgui


# Input
HEADERS += client_qt.h
SOURCES += main.cpp \
    client_qt.cpp
